email: vianney.mixtur@gmail.com
full_name: Vianney Mixtur
name: Vianney
background: Vianney is a software, data and AI engineer at MixIt. 
background_preferences: |

  Vianney has a wife Natacha Désirée Madelon - For emails related to our home or our son, you might want to transfer the messages to madelonat@yahoo.fr
  Other email addresses of interest - For emails related to my professional life, you might want to transfer the messages to vianney.mixtur@outlook.fr
  Newsletters and promotional emails - I receive way too much of those, maybe for the most relevant, generate a summary once a month.
timezone: "PST"
rewrite_preferences: |
  Vianney has a few rules for how he likes his emails to be written:

  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual
  - If working with an assistant to schedule, then he is usually more formal
  - If conversing with someone he seems to know well, then he is more direct and to the fact
  - Vianney REALLY does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Vianney
  - Vianney like short sentences.

triage_no: |
  - Automated emails from services that are spamming Vianney
  - Cold outreach from vendors - this happens a lot as people try to sell Vianney things. He is not interested in these, but maybe generate a summary once a moonth

triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Docusign things that needs to sign. These are using from Docusign and start with "Complete with Docusign". \
  Note: if the Docusign is already signed, you do NOT need to notify him. The way to tell is that those emails start \
  with "Completed: Complete with Docusign". Note the "Completed". Do not notify him if "Completed", only if still needs to be completed.
  - Anything that is pretty technically detailed about LangChain. Vianney sometimes gets asked questions about LangChain, \
  while he may not always respond to those he likes getting notified about them
  - Emails where there is a clear action item from Vianney based on a previous conversation, like adding people to a slack channel
triage_email: |
  - Emails from clients that explicitly ask Vianney a question
  - Emails from clients where someone else has scheduled a meeting for Vianney, and Vianney has not already chimed in to express his excitement
  - Emails from clients or potential customers where Vianney is the main driver of the conversation
  - Emails where Vianney has gotten added to a thread with a customer and he hasn't yet said hello
  - Emails where Vianney is introducing two people to each other. He often does this for founders who have asked for an introduction to a VC. If it seems like a founder is sending Vianney a deck to forward to other people, he should respond. If Vianney has already introduced the two parties, he should not respond unless they explicitly ask him a question.
  - Email from clients where they are trying to set up a time to meet
  - Emails where it seems like Vianney has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, Vianney should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, Vianney should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
